import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import React, { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const steps = [
    {
      content: "demographics",
      number: 1,
    },
    {
      content: "interests",
      number: 2,
    },
    {
      content: "flavors",
      number: 3,
    },
  ];
  const [step, setStep] = useState(steps[0]);

  return (
    <div>
      <Head>
        <title>Coconut</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p onClick={() => {
            
          }}>back</p>
          <p>{step["number"]}/3</p>
          <p>{step["content"]}</p>

        </div>
      </main>
    </div>
  );
}
